#!/bin/sh

set -e
exec 2>&1
set -u
set -x

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
  PKG_CONFIG="$DEB_HOST_GNU_TYPE-pkg-config"
else
  PKG_CONFIG="pkg-config"
fi

confflags=""
if [ -n "${DEB_BUILD_GNU_TYPE:-}" ] && [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
  if [ "$DEB_BUILD_GNU_TYPE" = "$DEB_HOST_GNU_TYPE" ]; then
    confflags="--build=$DEB_BUILD_GNU_TYPE"
  else
    confflags="--build=$DEB_BUILD_GNU_TYPE --host=$DEB_HOST_GNU_TYPE"
  fi
fi

CFLAGS=$($PKG_CONFIG --cflags libmd)
LDADD=$($PKG_CONFIG --libs libmd)

./configure $confflags
make
make -C test CFLAGS="$CFLAGS" LDADD="$LDADD" check
